#!/bin/sh

mkdir /tmp
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs none /tmp
mdev -s
/etc/init.d/rcS
ifconfig lo up

echo -e "Boot took $(cut -d' ' -f1 /proc/uptime) seconds"

poweroff -d 120000 -f &
setsid cttyhack setuidgid pwn /pwn

poweroff -d 0 -f
